### ISSUE TITLE
cannot load such file -- rack

### ISSUE THREAD

**Issue by Kajvdh** [YOU54F/pact_broker-serverless#103]
Hi,

I'm trying to get the serverless pact broker working using this fix: https://github.com/pact-foundation/pact_broker-serverless/commit/1171ad640af6fc6a8588969dc6f3a0db4b29f31d

It is now able to build succesfully & deploy the stack, but when I try to access the endpoint I receive this error:

```
{
    "errorMessage": "cannot load such file -- rack",
    "errorType": "Init<LoadError>",
    "stackTrace": [
        "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
        "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
        "/var/task/rack_adapter.rb:12:in `<top (required)>'",
        "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
        "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'"
    ]
}
```

Is it possible that this is also related to the bump of version 2.7?

**Comment by YOU54F** [comment]
Hi, no,  you most likely haven't download the pact broker source code, the error message is telling you it can't load the file.

https://github.com/pact-foundation/pact_broker-serverless/blob/master/serverless.yml#L30-L40

also note that branch is still a WIP until merged, and just as a note this entire project is _experimental_ at best :)

**Comment by YOU54F** [comment]
This has been merged to master now and tested, it's still as experimental as it was before but run on rb2.7 now
