### ISSUE TITLE
Ruby dependency error

### ISSUE THREAD

**Issue by charnjitsohal1** [YOU54F/pact_broker-serverless#99]
Hi,

I seem to be getting the following Ruby dependency error when running `make packagewithpg:`

```Step 4/6 : ADD pact_broker/Gemfile /var/task/Gemfile
 ---> 0e878fb313ce
Step 5/6 : ADD pact_broker/Gemfile.lock /var/task/Gemfile.lock
 ---> 13eedb62bed7
Step 6/6 : RUN bundle install && bundle install --deployment
 ---> Running in c09fb4182ef3
Fetching gem metadata from https://rubygems.org/.
..
......

dry-core-0.7.1 requires ruby version >= 2.6.0, which is incompatible with the
current version, ruby 2.5.8p224

The command '/bin/sh -c bundle install && bundle install --deployment' returned a non-zero code: 5
make: *** [Makefile:8: packagewithpg] Error 5```

**Comment by YOU54F** [comment]
Thanks @charnjitsohal1 

I think the base image will need to be updated

it currently uses `lambci/lambda:build-ruby2.5` they didn't do a 2.6 version but are on 2.7 now

https://hub.docker.com/layers/lambci/lambda/build-ruby2.7/images/sha256-7ca195b86ba116f5a4f43865ffbeeac534c72eb9a66bdba517c5fc53ef5c9c2f?context=explore

**Comment by YOU54F** [comment]
Was a little more involved, as pg isnt pinned in the Gemfile, so a bit of `sed` foo and its sorted.

https://github.com/pact-foundation/pact_broker-serverless/pull/89/commits/1171ad640af6fc6a8588969dc6f3a0db4b29f31d
